### ISSUE TITLE
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Terence233** [WillB97/pyapriltags#1]
Hi! I used the package on Ubuntu 20.04 and met the error below:

`OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/shengtao/anaconda3/envs/ens-target/lib/python3.7/site-packages/pyapriltags/./libapriltag.so)`

But the package works pretty well on Ubuntu 22.04. So I wonder if this package doesn't support old Ubuntu versions, like 20.04? 
I am a bit of a newb so I also want to know other solutions that don't break my system.

Thanks in advance!

**Comment by powei-lin** [comment]
The same here.

**Comment by WillB97** [comment]
I had been building the binaries in Ubuntu 22.04 which has a glibc version of 2.34. Anything ruung the binaries needed to have at least the same version of glibc. Since version 3.3.0.3 I've started using 20.04 which reduces this requirement to 2.31.
